Warning message:
In dir.create(args$output) : 'DE_data/MMRD/analysis_files' already exists
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'gs://cptac-pancan-getzlab/Final_Submission_Files/proteome_gene_centric.tsv.gz': No such file or directory
Execution halted
